project:
  type: website

website:
  title: "Quarto-Blog"

  page-footer:
      border: true

  navbar:
      right:
        - about.qmd
        - icon: github
          href: https://github.com/pinkocto

  sidebar:
    style: "docked"
    search: true
    contents:
      - 1_ip2022.qmd
      - 2_dv2022.qmd
      - 3_stbda2022.qmd
      - 5_stbda2023.qmd
      - 7_study.qmd
  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: false
    code-line-numbers: true
    code-copy: true
    