---
title: "JT test"
author: 'jiyun Lim'
date: '02/25/2023'
categories: 
  - R
format:
  html:
    theme: default
---

# JT-test

### Ex1

```{r}
library(tidyverse)
```

```{r}
group <- c(rep(3,8), rep(2,7), rep(1,7))
space <- c(54.0,67.0,47.2,71.1,62.7,44.8,67.4,80.2,
           79.8,82.0,88.8,79.6,85.7,81.7,88.5,
          98.6,99.5,95.8,93.3,98.9,91.1,94.5)
```

```{r, message=FALSE}
# H0: m_N = m_U = m_S
# H1: m_N >= m_U >= m_s (at least one strict inequality)
library(clinfun)
jonckheere.test(space, 
                group,
                alternative = 'decreasing')
```

### Large-Sample Approximation

For large sample sizes, J is approximately normally distributed with mean 0 and variance 1. When we use the normal approximation, we compute.

$$
z = \frac{J-[(N^2 - \sum_{i=1}^kn_i^2)/4]}{\sqrt{[N^2(2N+3)-\sum_{k=1}^kn_i^2(2n_i+3)]/72}}
$$
### Ex2
```{r}
jonckheere.test(mtcars$mpg,
                as.integer(mtcars$cyl),
                alternative = 'decreasing')
```

```{r}
N <- nrow(mtcars)
n1 <- filter(mtcars, mtcars$cyl == 4) %>% nrow()
n2 <- filter(mtcars, mtcars$cyl == 6) %>% nrow()
n3 <- filter(mtcars, mtcars$cyl == 8) %>% nrow()
```

```{r}
mu <- ((N^2 - (n1^2+n2^2+n3^2))/4)
var_ <- (N^2*(2*N+3)-((n1^2*(2*n1+3) + n2^2*(2*n2+3) + n3^2*(2*n3 + 3))))/72
mu; var_
```

```{r}
pnorm(5, mu, sqrt(var_), lower.tail = TRUE)
```

```{r}
z_ = (5 - mu) / sqrt(var_)
pnorm(z_,  lower.tail = TRUE)
```
